messages = {
    "pt_BR": {
        "openStar": "Nome do Ponto:",
        "starExistsError": "Já existe um ponto com esse nome.",
        "savePoints": "Pressione F10 para Salvar os Pontos",
        "loadPoints": "Pressione F11 para Carregar os Pontos",
        "deletePoints": "Pressione F12 para Deletar os Pontos",
        "saveSuccess": "Pontos salvos com sucesso!",
        "loadSuccess": "Pontos carregados com sucesso!",
        "fileNotFound": "Arquivo não encontrado.",
        "deleteConfirm": "Tem certeza de que deseja deletar os pontos?",
        "deleteSuccess": "Arquivo e pontos deletados com sucesso!",
        "deleteNoFile": "Não foram encontrados arquivos ou pontos para serem apagados",
        "errorSave": "Erro ao salvar pontos",
        "errorLoad": "Erro ao carregar pontos",
        "errorDelete": "Erro ao deletar arquivo e pontos",
        "developedBy": "Desenvolvido por Stefano Augusto Mossi",
        "courseInfo": "Ciências da Computação - Atitus - 2023/1",
    },
    "en_US": {
        "openStar": "Point Name:",
        "starExistsError": "A point with that name already exists.",
        "savePoints": "Press F10 to Save Points",
        "loadPoints": "Press F11 to Load Points",
        "deletePoints": "Press F12 to Delete Points",
        "saveSuccess": "Points saved successfully!",
        "loadSuccess": "Points loaded successfully!",
        "deleteConfirm": "Are you sure you want to delete the points?",
        "deleteSuccess": "File and points deleted successfully!",
        "deleteNoFile": "No files or points found to delete",
        "errorSave": "Error saving points",
        "errorLoad": "Error loading points",
        "errorDelete": "Error deleting file and points",
        "developedBy": "Developed by Stefano Augusto Mossi",
        "courseInfo": "Computer Science - Atitus - 2023/1",
    }
}